// <auto-generated />
using AgencyService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgencyService.Migrations
{
    [DbContext(typeof(AgencyServiceDBContext))]
    [Migration("20231118181621_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AgencyService.Models.ServiceOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("AgencyService.Models.ServiceOfferItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyPrice")
                        .HasColumnType("int");

                    b.Property<string>("OfferName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("CODIFICATION_OF_LAWS");

                    b.Property<int>("YearlyPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OfferItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAccepted = false,
                            MonthlyPrice = 250,
                            OfferName = "CODIFICATION_OF_LAWS",
                            YearlyPrice = 1250
                        });
                });

            modelBuilder.Entity("ServiceOfferServiceOfferItem", b =>
                {
                    b.Property<int>("ServiceOfferItemsId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOffersId")
                        .HasColumnType("int");

                    b.HasKey("ServiceOfferItemsId", "ServiceOffersId");

                    b.HasIndex("ServiceOffersId");

                    b.ToTable("ServiceOfferServiceOfferItem");
                });

            modelBuilder.Entity("ServiceOfferServiceOfferItem", b =>
                {
                    b.HasOne("AgencyService.Models.ServiceOfferItem", null)
                        .WithMany()
                        .HasForeignKey("ServiceOfferItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyService.Models.ServiceOffer", null)
                        .WithMany()
                        .HasForeignKey("ServiceOffersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
