namespace AuthService.Enums
{
    public enum EUserType
    {
        AGENCY_REGISTRATION_EMPLOYEE,
        AGENCY_REGISTRATION_DIRECTOR,
        AGENCY_CODIFICATION_LAYER,
        AGENCY_CODIFICATION_DIRECTOR,
        GOVERNMENT_PRIME_MINISTER,
        GOVERNMENT_DIRECTOR,
        GOVERNMENT_EMPLOYEE
    }
}
